### ISSUE TITLE
Tested on Win 7, hide wireframes is not working.

### ISSUE THREAD

**Issue by newemka** [baku89/VirtualMapper#2]
Everything is working good except wireframe visibility, Wireframes remain visible even after checking and unchecking the button.  This happens only with obj files.

**Comment by baku89** [comment]
Thanks for reporting!
I'll check this problem, but bug fix may be delayed because of my develpment environment.
(it's mac and could only test on Win 7 running on VMWare.)

**Comment by newemka** [comment]
Don't worry! take the time you need. There's no rush.  I enjoy beta testing if needed.

**Comment by baku89** [comment]
The latest version v2.3.1 for Windows would work fine!
Thanks again for reporting 👍
