### ISSUE TITLE
Expand how-to

### ISSUE THREAD

**Issue by mruegenberg** [baku89/VirtualMapper#4]
Hi,
I would like to use VirtualMapper because it seems to be easy to set up.

However, I'm a bit lost with how to use it. 
I got that I need to start some Spout sender, and load my 3D model. 

Am I correct in assuming that I basically create a cam for my projector in VirtualMapper and try to move it so that the projected image is on my projection surface without distortion?
Also, is it possible to use full screen?

**Comment by newemka** [comment]
Hi, VirtualMapper is a realtime _PREVIEW_ tool for projection mapping. this
means there is not feature for doing projection mapping, You will need to
use an other software to achieve what you want.

OfxPimapper, vvvv, madmapper, resolume arena 5, mapio...

2016-04-13 17:52 GMT+02:00 Marcel Ruegenberg notifications@github.com:

**Comment by mruegenberg** [comment]
Thanks, that clarifies things.

**Comment by baku89** [comment]
Thanks for asking, @newemka.
I'll append and emphasize that this software is just a preview utility in how-to.
